# Feedback

I am a bit frustrated that the default way numpy does array multiplication is not by the dot product method, but instead is element based.

Besides that, straightforward. Thanks Paul!

# 6.2 (What’s Wrong with This Code?)  
The following code should display the unique words in the string text and the number of occurrences of each word.  

```python
from collections import Counter

text = ('to be or not to be that is the question')
counter = Counter(text.split())

for word, count in sorted(counter):
    print(f'{word:<12}{count}')
```

In [3]:
# fixed with counter.items()
from collections import Counter

text = ('to be or not to be that is the question')
counter = Counter(text.split())

for word, count in sorted(counter.items()):
    print(f'{word:<12}{count}')

be          2
is          1
not         1
or          1
question    1
that        1
the         1
to          2


The for loop above needs a list of tuples to loop through, rather than the dictionary itself. In order to acheive this, we use the .items() method.

# 6.3 (What Does This Code Do?)  
The dictionary temperatures contains three Fahrenheit temperature samples for each of four days. What does the for statement do?
```python
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}

for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')
```

In [4]:
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}

for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')

Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00


This code loops through the items in this dictionary and finds the average of the values associated with each key. It does this by summing the list of values associated with each key, and then dividing the sum by the length of the list of those values, which should equal the number of temperatures of that day. It then returns the results formatted at 2 decimal places.

# 6.6 (Duplicate Word Removal)  
Write a function that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a set to get the unique words in the list. Test your function with several sentences.

In [61]:
from numpy import unique

list_of_words = ["These", "are", "the", "words", "THAT", "THE", "list", "neEd", "tO", "look", "at", "and", "THE", "WoRds", "are", "DIFFERENT"]
list_of_words2 = ["WHAT", "do", "YOU", "think", "OF", "this", "SentENCE", "PAUL", "WHAT", "DO", "YOU", "THINK"]
list_of_words3 = ["PYTHON", "is", "fuuunn", "DUH", "FUUUNN"]

def unique_sorted_words(words):
    "Returns an alphabetized list of unique words"
    lower = []
    for i in words:
       lower.append(i.lower())
    
    lower.sort()
    lower = enumerate(unique(lower))
    return lower

print("  Unique Words  ")
print("----------------")
for number, word in unique_sorted_words(list_of_words):
     print(f'{number + 1:>2}){word:>13}')

print()
print("  Unique Words  ")
print("----------------")
for number, word in unique_sorted_words(list_of_words2):
     print(f'{number + 1:>2}){word:>13}')

print()
print("  Unique Words  ")
print("----------------")
for number, word in unique_sorted_words(list_of_words3):
     print(f'{number + 1:>2}){word:>13}')

  Unique Words  
----------------
 1)          and
 2)          are
 3)           at
 4)    different
 5)         list
 6)         look
 7)         need
 8)         that
 9)          the
10)        these
11)           to
12)        words

  Unique Words  
----------------
 1)           do
 2)           of
 3)         paul
 4)     sentence
 5)        think
 6)         this
 7)         what
 8)          you

  Unique Words  
----------------
 1)          duh
 2)       fuuunn
 3)           is
 4)       python


# (Dictionary Manipulations)  
Using the following dictionary, which maps country names to Internet top-level domains (TLDs):
```python
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}
```
Perform the following tasks and display the results:  
> a) Check whether the dictionary contains the key 'Canada'.  
b) Check whether the dictionary contains the key 'France'.  
c) Iterate through the key–value pairs and display them in two-column format.  
d) Add the key–value pair 'Sweden' and 'sw' (which is incorrect).  
e) Update the value for the key 'Sweden' to 'se'.  
f) Use a dictionary comprehension to reverse the keys and values.  
g) With the result of part (f), use a dictionary comprehension to convert the country
names to all uppercase letters.  

In [127]:
tlds = {"Canada": "ca", "United States": "us", "Mexico": "mx"}
# Check whether the dictionary contains the key 'Canada'.
if "Canada" in tlds.keys():
    print("Canada is in Keys")
else:
    print("Canada is not in Keys")

# Check whether the dictionary contains the key 'France'.
if "France" in tlds.keys():
    print("France is in Keys")
else:
    print("France is not in Keys")

# Iterate through the key–value pairs and display them in two-column format.
print()
print(" " * 12,"Key", "  ", "Value")
print("-" * 25)
for key, value in tlds.items():
     print(f'{key:>15} :{value:>8}')

# Add the key–value pair 'Sweden' and 'sw' (which is incorrect).
tlds["Sweden"] = "sw"
print()
print(" " * 12,"Key", "  ", "Value")
print("-" * 25)
for key, value in tlds.items():
     print(f'{key:>15} :{value:>8}')

# Update the value for the key 'Sweden' to 'se'.
tlds["Sweden"] = "se"
print()
print(" " * 12,"Key", "  ", "Value")
print("-" * 25)
for key, value in tlds.items():
     print(f'{key:>15} :{value:>8}')

# Use a dictionary comprehension to reverse the keys and values.
flipped_tlds = {tld: name for name, tld in tlds.items()}
print()
print("Key", " " * 9, "Value")
print("-" * 19)
for key, value in flipped_tlds.items():
     print(f'{key:>2} :{value:>15}')
     
# With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.
flipped_tlds = {tld.upper(): name for tld, name in flipped_tlds.items()}
print()
print("Key", " " * 9, "Value")
print("-" * 19)
for key, value in flipped_tlds.items():
     print(f'{key:>2} :{value:>15}')

Canada is in Keys
France is not in Keys

             Key    Value
-------------------------
         Canada :      ca
  United States :      us
         Mexico :      mx

             Key    Value
-------------------------
         Canada :      ca
  United States :      us
         Mexico :      mx
         Sweden :      sw

             Key    Value
-------------------------
         Canada :      ca
  United States :      us
         Mexico :      mx
         Sweden :      se

Key           Value
-------------------
ca :         Canada
us :  United States
mx :         Mexico
se :         Sweden

Key           Value
-------------------
CA :         Canada
US :  United States
MX :         Mexico
SE :         Sweden


# 7.2 (Broadcasting)  
Use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:  
> a) Cube every element of the array.  
b) Add 7 to every element of the array.  
c) Multiply every element of the array by 2.  

In [171]:
import numpy as np

array = np.arange(4).reshape(2,2)

print(array ** 3, "\n")
print(array + 7, "\n")
print(array * 2, "\n")

[[ 0  1]
 [ 8 27]] 

[[ 7  8]
 [ 9 10]] 

[[0 2]
 [4 6]] 



# 7.3 (Element-Wise array Multiplication)  
Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9
down to 1, then multiply the first array by the second.

In [165]:
import numpy as np

array = np.arange(2, 19, 2).reshape(3,3)
array2 = np.arange(9, 0, -1).reshape(3,3)

print(array, "\n")
print(array2)

array * array2


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

# 7.9 (Indexing and Slicing arrays)  
Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:  

> a) Select row 2.  
b) Select column 5.  
c) Select rows 0 and 1.  
d) Select columns 2–4.  
e) Select the element that is in row 1 and column 4.  
f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.  

In [163]:
import numpy as np

array = np.arange(1, 16).reshape(3,5)

# Select row 2.  
print(array[2,:], "\n")

# Select column 5 (4).  
print(array[:,4], "\n")

# Select rows 0 and 1.  
print(array[[0,1],:], "\n")

# Select columns 2–4.  
print(array[:,2:4], "\n")

# Select the element that is in row 1 and column 4.
print(array[1,4], "\n")

# Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
print(array[1:2,1:4:2])

[11 12 13 14 15] 

[ 5 10 15] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[ 3  4]
 [ 8  9]
 [13 14]] 

10 

[[7 9]]


# 7.14 (Horizontal and Vertical Stacking)  
Create the two-dimensional arrays
```python
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
```
> a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.  
b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.  
c) Use vertical stacking with two copies of array4 to create a 4-by-4 array5.  
d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.  

In [170]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.  
array3 = np.vstack((array1, array2))
print(array3, "\n")

# Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.  
array4 = np.hstack((array1, array2))
print(array4, "\n")

# Use vertical stacking with two copies of array4 to create a 4-by-4 array5.  
array5 = np.vstack((array4, array4))
print(array5, "\n")

# Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.  
array6 = np.hstack((array3, array3))
print(array6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1 4 5]
 [2 3 6 7]] 

[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]] 

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
